# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    # Specify the Xcode version to use
    macos:
      xcode: "12.0.0"
    shell: /bin/bash --login -eo pipefail
    environment:
      PROJECT_NAME: "ZappPlugins"
      SCHEME_NAME: "ZappPlugins"
      SCRIPTS_LOCAL_FOLDER: "~/.scripts-iOS"
      SCRIPTS_REPO_PATH: "git@github.com:applicaster/Scripts-iOS.git"
      DEPLOY_VERSION: "0.17.6"
      DEPLOY_COMMAND: "~/.scripts-iOS/circleCi/deploySingleXCFrameworkMultiPlatform.sh"
    working_directory: ~/ZappPlugins-iOS
    steps:
      - run:
          name: Ruby - set version
          command: echo "ruby-2.5" > ~/.ruby-version

      - run:
          name: Ruby - version
          command: ruby -v

      # Prepere Git and Submodules
      - restore_cache:
          keys:
            - Zapp-Plugins-v5.1-{{ .Branch }}-{{ .Revision }}
            - Zapp-Plugins-v5.1-{{ .Branch }}-
            - Zapp-Plugins-v5.1-

      - checkout

      - save_cache:
          name: Git - save cache
          key: Zapp-Plugins-v5.1-{{ .Branch }}-{{ .Revision }}-{{ .Environment.version_id }}
          paths:
            - ".git"

      - run:
          name: Adding scripts
          command: |
            if [ ! -d "$SCRIPTS_LOCAL_FOLDER" ]; then
              git clone $SCRIPTS_REPO_PATH $SCRIPTS_LOCAL_FOLDER
            else
              echo "Repo exists in local path: $SCRIPTS_LOCAL_FOLDER"
              git -C $SCRIPTS_LOCAL_FOLDER fetch
              git -C $SCRIPTS_LOCAL_FOLDER fetch --tags
              git -C $SCRIPTS_LOCAL_FOLDER checkout
              git -C $SCRIPTS_LOCAL_FOLDER pull origin master
            fi
            git -C $SCRIPTS_LOCAL_FOLDER checkout $DEPLOY_VERSION

      # Prepare Bundler
      - restore_cache:
          name: Bundler - restore cache
          key: Zapp-Plugins-v1-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundler - install dependencies
          command: bundle install

      - save_cache:
          name: Bundler - save cache
          key: Zapp-Plugins-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - /Users/distiller/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems

      # Restore Cocoapods cache, save cache on lower level, after pod update
      - restore_cache:
          name: CocoaPods - restore cache
          key: Zapp-Plugins-10

      - run:
          name: CocoaPods - version
          command: bundle exec pod --version

      # Pod update
      - run:
          name: CocoaPods - update dependencies
          command: bundle exec pod install

      # Cache CocoaPods
      - save_cache:
          name: CocoaPods - save cache
          key: Zapp-Plugins-10
          paths:
            - "./Pods"
            - "~/.cocoapods/repos/cocoapods-"

      # Tests
      - run:
          name: Tests - start
          command: bundle exec fastlane ios test

      # Deploy
      - deploy:
          name: Creating Closed SDK version
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ] || [[ "$CIRCLE_BRANCH" == "hotfix_"* ]];
            then
              echo "Execute deploy script"
              $DEPLOY_COMMAND $PROJECT_NAME
            else
              echo "Branch is not master, deploy process will be skipped"
            fi

      - store_test_results:
          path: ./CircleArtifacts/test-results

      - store_artifacts:
          path: ./CircleArtifacts

workflows:
  version: 2
  build:
    jobs:
      - build
